version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies (none for static site)..."
  build:
    commands:
      - echo "Building static website..."
      - echo "Build complete!"
artifacts:
  files:
    - '**/*'

